### ISSUE TITLE
Support importing from Vector DBs

### ISSUE THREAD

**Issue by enjalot** [enjalot/latent-scope#28]
Related to #13 it would be great to enable easy importing of embeddings + metadata from an existing vectordb like Pinecone, Chroma, Supabase, postgres or mongo.

My main question is how the interface should look, both UI and via python.

I'm imagining people want to specify their database connection info and the desired table to import. we would then query and save it into latent scope folders as input.parquet and save the embeddings in h5.

An example motivating use case would be helpful to build against, especially with data loaded.

**Comment by dhruv-anand-aintech** [comment]
I think Vector-io can help here: https://github.com/enjalot/latent-scope/issues/29

Basically, 
Step 1: use vector-io to export index to a vector dataset in vdf format.
Step 2: Feed in the resultant parquet file/s into latentscope.

**Comment by enjalot** [comment]
that sounds like a very reasonable approach. I made some progress on a python API for importing embeddings in #13

**Comment by enjalot** [comment]
Importing embeddings that are in the input parquet/csv is now supported via the web ui as per #34 
<img width="1100" alt="Screenshot 2024-03-21 at 3 12 42 PM" src="https://github.com/enjalot/latent-scope/assets/96189/9ecabfab-ab86-4830-bd5b-fe2c7e57422b">

**Comment by dhruv-anand-aintech** [comment]
not seeing the option for some reason (v0.1.8)
![Screenshot 2024-03-22 at 11 46 27 AM](https://github.com/enjalot/latent-scope/assets/105786647/89148c25-a901-4780-8bc5-93a7a72ffda1)

**Comment by dhruv-anand-aintech** [comment]
ok, importing it afresh does the trick

**Comment by dhruv-anand-aintech** [comment]
clicking on the yes doesn't do anything
![Screenshot 2024-03-22 at 11 52 49 AM](https://github.com/enjalot/latent-scope/assets/105786647/f54d7ab4-65a8-4e71-98ba-b72cbff97b4f)

**Comment by enjalot** [comment]
@dhruv-anand-aintech when you click yes does it say anything in the web console or in the server terminal?
its supposed to start a job that processes the column into a embedding file

**Comment by dhruv-anand-aintech** [comment]
Nothing on server logs.
Last part of this on web console:
```
 styles Object
 ENV Object
 scopes Object
 scopes Object
 scopes Object
 scopes Object
 scopes Object
cluster-004.png:1  Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-001.png:1  Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-002.png:1  Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-001.png:1  Failed to load resource: the server responded with a status of 404 (NOT FOUND)
index--6zMdD4M.js:543 DATASET Object
index--6zMdD4M.js:543 fetching scopes
cluster-004.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
:5001/api/files/Reels/umaps/umap-001.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
:5001/api/files/Reels/clusters/cluster-003.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-002.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-001.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
index--6zMdD4M.js:534 fresh draw scatterplot
index--6zMdD4M.js:534 transitioning scatterplot
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
index--6zMdD4M.js:68 scopes Object
cluster-001.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-004.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-002.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
cluster-001.png:1 
        
        
       Failed to load resource: the server responded with a status of 404 (NOT FOUND)
index--6zMdD4M.js:68 is name taken? true info_map Array(6)
index--6zMdD4M.js:68 Job ID: f0e3351f-3f4a-46ca-bb80-60f163608d08
index--6zMdD4M.js:67 start polling f0e3351f-3f4a-46ca-bb80-60f163608d08
index--6zMdD4M.js:67 returning jobPolling cleanup
index--6zMdD4M.js:67 polling job status Object
index--6zMdD4M.js:67 polling job status Object
index--6zMdD4M.js:67 polling job status Object
index--6zMdD4M.js:543 DATASET Object
index--6zMdD4M.js:543 POTENTIAL EMBEDDINGS Array(2)0: "vec_input_prompt_huggingface_jinaai_jina-embeddings-v2-base-en"1: "vec_input_prompt_huggingface_sentence-transformers_all-MiniLM-L6-v2"length: 2[[Prototype]]: Array(0)at: ƒ at()concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()findLast: ƒ findLast()findLastIndex: ƒ findLastIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toReversed: ƒ toReversed()toSorted: ƒ toSorted()toSpliced: ƒ toSpliced()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()with: ƒ with()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {at: true, copyWithin: true, entries: true, fill: true, find: true, …}[[Prototype]]: Object
index--6zMdD4M.js:543 fetching scopes
index--6zMdD4M.js:543 Uncaught TypeError: Failed to construct 'FormData': parameter 1 is not of type 'HTMLFormElement'.
    at index--6zMdD4M.js:543:3078
    at onClick (index--6zMdD4M.js:543:4930)
    at Object.w7 (index--6zMdD4M.js:37:9864)
    at S7 (index--6zMdD4M.js:37:10018)
    at b7 (index--6zMdD4M.js:37:10075)
    at Gy (index--6zMdD4M.js:37:31462)
    at c5 (index--6zMdD4M.js:37:31879)
    at index--6zMdD4M.js:37:36792
    at U2 (index--6zMdD4M.js:40:36957)
    at M4 (index--6zMdD4M.js:37:8999)
(anonymous) @ index--6zMdD4M.js:543
onClick @ index--6zMdD4M.js:543
w7 @ index--6zMdD4M.js:37
S7 @ index--6zMdD4M.js:37
b7 @ index--6zMdD4M.js:37
Gy @ index--6zMdD4M.js:37
c5 @ index--6zMdD4M.js:37
(anonymous) @ index--6zMdD4M.js:37
U2 @ index--6zMdD4M.js:40
M4 @ index--6zMdD4M.js:37
Kp @ index--6zMdD4M.js:37
v2 @ index--6zMdD4M.js:37
B7 @ index--6zMdD4M.js:37
```

**Comment by enjalot** [comment]
I'm going to close this in favor of #60 since we now support importing existing embeddings.
